kafka-demo2:
  topic-name: db-index
  response-topic-name: db-response

spring:
  kafka:
    bootstrap-servers: localhost:29092
#    consumer.auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
